---
<% if begin; File.read('/sys/fs/selinux/enforce') == '1'; rescue Errno::ENOENT => e; false; end %><% @SELinux=true %><% end %>
driver:
  name: docker
  use_sudo: false
  privileged: true

verifier:
  name: inspec
  format: doc

provisioner:
  name: salt_solo
  salt_install: bootstrap
  salt_bootstrap_url: https://bootstrap.saltstack.com
  salt_bootstrap_options: -p git -p curl stable 2016.11
  salt_version: latest
  log_level: debug
  require_chef: false
  formula: vault

platforms:
  - name: ubuntu-16.04
    driver_config:
      provision_command:
        - apt-get update && apt-get install -y locales && locale-gen en_US.UTF-8
      run_command: /sbin/init
      pid_one_command: /usr/lib/systemd/systemd
  - name: centos-7
    <% if @SELinux %>
    driver:
      name: vagrant
      provider: libvirt
      box: centos/7
    <% end %>
    driver_config:
      run_command: /sbin/init
      pid_one_command: /usr/lib/systemd/systemd
  - name: amazonlinux
    driver_config:
      provision_command:
        - yum install -y epel-release
      image: amazonlinux:latest
      platform: rhel
      run_command: /sbin/init

suites:
  - name: dev_server_systemd
    excludes:
      - amazonlinux
    provisioner:
      state_top:
        base:
          '*':
            - vault
            - vault.server
      pillars:
        top.sls:
          base:
            '*':
              - vault
        vault.sls:
          vault:
            service:
              type: systemd
  - name: dev_server_upstart_s3
    includes:
      - amazonlinux
    provisioner:
      state_top:
        base:
          '*':
            - vault
            - vault.server
      pillars:
        top.sls:
          base:
            '*':
              - vault
        vault.sls:
          vault:
            service:
              type: upstart
            backend:
              type: s3
              bucket: com-saltstack-vault
