---
driver:
  name: vagrant
  hostname: freebsd.ci.local
  cache_directory: false
  customize:
    memory: 512
  provision: true
  vagrantfiles:
    - .freebsd_provision.rb

verifier:
  name: inspec

platforms:
  - name: freebsd-11

provisioner:
  name: salt_solo
  salt_version: latest
  log_level: info
  require_chef: false
  formula: vault

driver_config:
  boot_timeout: 1200

suites:
  - name: install_binary
    provisioner:
      state_top:
        base:
          '*':
            - vault.package
      pillars:
        top.sls:
          base:
            '*':
              - vault
        vault.sls:
          vault:
#            version: 1.0.3    # test upgrades by doing a double-converge, changing the version pillar between each one
            version: 1.1.0
            verify_download: False

  - name: dev_server
    provisioner:
      state_top:
        base:
          '*':
            - vault
      pillars:
        top.sls:
          base:
            '*':
              - vault
        vault.sls:
          vault:
            dev_mode: True
  - name: prod_server
    provisioner:
      state_top:
        base:
          '*':
            - vault
      pillars:
        top.sls:
          base:
            '*':
              - vault
        vault.sls:
          vault:
            config:
              storage:
                file:
                  path: /var/lib/vault/data
            tls_disable: 1
            self_signed_cert:
              enabled: True
              hostname: localhost
              password: localhost
              country: GB
              state: England
              city: London
              org: example.com
              org_unit: testing

