---
driver:
  name: docker
  use_sudo: false
  privileged: true

provisioner:
  name: salt_solo
  log_level: debug
  require_chef: false
  formula: vault
  state_top:
    base:
      '*':
        - vault
  pillars:
    top.sls:
      base:
        '*':
          - vault
    vault.sls:
      vault:
        vault_version: '0.7.0'



platforms:
  - name: centos-6.4
  - name: centos-7
  - name: ubuntu-14.04
  - name: debian-jessie
    driver_config:
      run_command: /sbin/init

suites:
  - name: default

verifier:
  name: inspec
  format: doc
