---
name: Test & release

'on':
  - pull_request
  - push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != format('refs/heads/{0}',
                          github.event.repository.default_branch) }}

jobs:
  should-run:
    name: Prep / Should run
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      should-run: ${{ steps.action.outputs.should-run }}
    steps:
      - id: action
        # yamllint disable-line rule:line-length
        uses: techneg-it/should-workflow-run@eff19348eb884f57e05bc6f05ae48ece3af14714 # v1.0.1
  pre-commit:
    name: Lint / `pre-commit`
    needs: should-run
    if: fromJSON(needs.should-run.outputs.should-run)
    container: techneg/ci-pre-commit:v2.4.26@sha256:60f5e15b35fd93a16bff63a6af078f2e61ca06baf1db18a7b30ebaf121f309ba
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          fetch-tags: true
          filter: tree:0
      - name: Export `CI_CACHE_ID` from container
        run: echo "CI_CACHE_ID=$(cat /.ci_cache_id)" >> $GITHUB_ENV
      - uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: ~/.cache/pre-commit
          key: "${{ env.CI_CACHE_ID }}|\
                ${{ hashFiles('.pre-commit-config.yaml') }}"
      - name: Run `pre-commit`
        run: |
          git config --global --add safe.directory $(pwd)
          pre-commit run --all-files --color always --verbose
          pre-commit run --color always --hook-stage manual commitlint-ci
  test:
    name: Test / Kitchen
    needs:
      - pre-commit
      - should-run
    if: fromJSON(needs.should-run.outputs.should-run)
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        platform:
          - debian-12-master
          - debian-11-master
          - ubuntu-2404-master
          - ubuntu-2204-master
          - ubuntu-2004-master
          - debian-12-3007-4
          - debian-11-3007-4
          - ubuntu-2404-3007-4
          - ubuntu-2204-3007-4
          - ubuntu-2004-3007-4
          - debian-12-3006-12
          - debian-11-3006-12
          - ubuntu-2404-3006-12
          - ubuntu-2204-3006-12
          - ubuntu-2004-3006-12
    steps:
      - name: Debug on runner (When re-run with "Enable debug logging" checked)
        if: runner.debug
        uses: mxschmitt/action-tmate@7b6a61a73bbb9793cb80ad69b8dd8ac19261834c # v3.22
        with:
          detached: true
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: ruby/setup-ruby@a4effe49ee8ee5b8b5091268c473a4628afb5651 # v1.245.0
        with:
          bundler-cache: true
          ruby-version: '3.1'
      - run: |
          bin/kitchen verify ${{ matrix.platform }}
  results:
    name: Release / Collect results
    permissions:
      checks: read
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      # yamllint disable-line rule:line-length
      - uses: poseidon/wait-for-status-checks@899c768d191b56eef585c18f8558da19e1f3e707 # v0.6.0
        with:
          ignore: >
            Release / Collect results,
            Test / Kitchen (debian-12-master),
            Test / Kitchen (debian-11-master),
            Test / Kitchen (ubuntu-2404-master),
            Test / Kitchen (ubuntu-2204-master),
            Test / Kitchen (ubuntu-2004-master)
          ignore_pattern: ^GitLab CI
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: echo "::notice ::Workflow success!"
